services:
  gradio:
    build: .
    container_name: gradio
    volumes:
      - shared_db_volume:/app/db
      - /etc/letsencrypt/live/pierrechaumont.fr/:/etc/letsencrypt/live/pierrechaumont.fr/
    ports:
      - "7860:7860"

  airflow:
    build:
      context: ./airflow
    container_name: airflow
    volumes:
      - shared_db_volume:/opt/db
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_HOME=${AIRFLOW__CORE__DEFAULT_TIMEZONE}
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=${AIRFLOW__CORE__DEFAULT_TIMEZONE}
      - AIRFLOW__WEBSERVER__AUTHENTICATE=${AIRFLOW__WEBSERVER__AUTHENTICATE}
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=${AIRFLOW__WEBSERVER__AUTH_BACKEND}

volumes:
  shared_db_volume:
