services:
  gradio:
    build: .
    container_name: gradio
    volumes:
      - shared_db_volume:/app/db
    ports:
      - "7860:7860"

  airflow:
    build:
      context: ./airflow
    container_name: airflow
    volumes:
      - shared_db_volume:/opt/airflow/db
    ports:
      - "8080:8080"

volumes:
  shared_db_volume:
